---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asynqmon-deployment
  labels:
    app: asynqmon
spec:
  selector:
    matchLabels:
      app: asynqmon
  template:
    metadata:
      labels:
        app: asynqmon
    spec:
      volumes:
        - name: redis
          secret:
            secretName: redis-secrets-asynq
            items:
              - key: REDIS_CA_CERT
                path: ca.pem
              - key: REDIS_CERT
                path: cert.pem
              - key: REDIS_CERT_KEY
                path: key.pem
      containers:
        - name: asynqmon
          image: undead/asyncmon:v0.7.2
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          args:
            - --redis-tls
            - redis-host.0000.us-central1-1.gce.cloud.redislabs.com
            - --redis-ca
            - /tmp/secrets/ca.pem
            - --redis-cert
            - /tmp/secrets/cert.pem
            - --redis-key
            - /tmp/secrets/key.pem
          envFrom:
            - secretRef:
                name: redis-secrets-asynq
          volumeMounts:
            - name: redis
              mountPath: "/tmp/secrets"
              readOnly: true

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: asynqmon-service
  labels:
    app: asynqmon
spec:
  type: ClusterIP
  selector:
    app: asynqmon
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
